In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./translated_text_with_other_data.csv', encoding='utf-8-sig')

In [5]:
df_clean = df.drop(columns=['followers', 're_followers', 're_gender', 're_location', 're_mid', 're_time', 're_uid', 'text'])
df_clean

,_id,gender,location,time,uid,gender_label,text_eng
0,4778778284788623,m,广东,"2022/06/10, 11:49:51",7319642154,2.0,A group of big men touched other women's women...
1,4778788178625613,m,广东,"2022/06/10, 12:29:10",6420207784,2.0,"Molesting a beautiful woman was rejected, and ..."
2,4778791911558944,m,湖北,"2022/06/10, 12:44:00",6078562289,1.0,What a disgrace to a man! Those who touch othe...
3,4778793132884451,m,广东,"2022/06/10, 12:48:50",7319642154,2.0,Molesting a beautiful woman in public was reje...
4,4778794802745132,f,广东,"2022/06/10, 12:55:29",5752980584,0.0,Two men beat her up when they failed to ask fo...
...,...,...,...,...,...,...,...
645859,4786515714509930,f,广东,"2022/07/01, 20:15:38",7746467515,2.0,"After so many days, the current situation of t..."
645860,4786527463279012,m,山东,"2022/07/01, 21:02:19",7024438800,2.0,sunshine
645861,4786528877022355,m,广西,"2022/07/01, 21:07:56",7558373492,2.0,Where did those four girls go? The media can't...
645862,4786538246574989,f,北京,"2022/07/01, 21:45:10",6130628947,2.0,"Wait for the follow-up, wait for the follow-up..."
645863,4786555942604635,f,北京,"2022/07/01, 22:55:29",2181580185,2.0,What is this sealing? ? ?

In [7]:
df_clean.to_csv('translated_text_with_other_data (cleaned).csv', index=False, encoding='utf-8-sig')